title: Pedro Camellon
description: AI/ML Engineer, Cloud Architect
url: "https://pedropcamellon.github.io"
baseurl: ""
markdown: kramdown

# Include _tabs folder
include:
  - _tabs

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
